sudo: true
dist: trusty
language: cpp

# Install packages
install:
    - sudo apt-get update
    - sudo apt-get install qt5-default qttools5-dev-tools libboost-dev -y
    - mkdir build
    - cd build
    - cmake ..
    - make

# For GUI testing
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# Run tests
script:
    - env CTEST_OUTPUT_ON_FAILURE=1 make test