sudo: true
dist: trusty
language: cpp

# Install packages
install:
    - sudo apt-get update
    - sudo apt-get install qt5-default qttools5-dev-tools -y
    - mkdir build
    - cd build
    - cmake ..
    - make

# Run tests
script:
    - QT_QPA_PLATFORM='offscreen'
    - env CTEST_OUTPUT_ON_FAILURE=1 make test