sudo: true
dist: trusty
language: cpp

# Install packages
install:
    - sudo apt-get update
    - sudo apt-get install qt5-default qttools5-dev-tools -y

script:
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
    - make test