sudo: required

language: cpp

# Install packages
install:
    - sudo apt-get update
    - sudo apt-get install qt5-default qttools5-dev-tools
    - mkdir build
    - cd build
    - cmake ..
    - make
