sudo: true
dist: trusty
language: cpp

# For GUI testing
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep

# Install packages
install:
    - sudo apt-get update
    - sudo apt-get install qt5-default qttools5-dev-tools -y
    - mkdir build
    - cd build
    - cmake ..
    - make

# Run tests
script:
    - env CTEST_OUTPUT_ON_FAILURE=1 make test